services:
  api-comandvoice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-comandvoice-container
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_URL_RECEPTIONIST=${N8N_WEBHOOK_URL_RECEPTIONIST}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOGGING_FILE_NAME=/app/logs/application.log
    volumes:
      - ./logs:/app/logs
    networks:
      - comandvoice-network
    restart: always
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-container
    restart: always
    environment:
      - GRAFANA_LOKI_URL=${GRAFANA_LOKI_URL}
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/api:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    networks:
      - comandvoice-network
    depends_on:
      - api-comandvoice

  db:
    image: postgres:16-alpine
    container_name: db-comandvoice
    restart: always
    shm_size: '256mb'
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - comandvoice-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  comandvoice-network:
    driver: bridge