services:
  api-comandvoice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-comandvoice-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - LOGGING_FILE_NAME=/app/logs/application.log
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/app/logs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy # Garante que a API só tenta ligar DEPOIS que o Postgres estiver aceitando conexões

  betterstack-collector:
    image: ghcr.io/betterstackhq/collector:latest
    container_name: better-stack-collector
    restart: always
    uts: host
    environment:
      - COLLECTOR_SECRET=${TOKEN_LOG}
      - VECTOR_LOG_FORMAT=json
    volumes:
      - /:/host:ro
      - /var/lib/better-stack:/var/lib/better-stack
    depends_on:
      - api-comandvoice

  db:
    image: postgres:16-alpine
    container_name: db-comandvoice
    restart: always
    shm_size: '256mb'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: