version: '3.8'

services:
  api-comandvoice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-comandvoice-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      # DIRECIONA OS LOGS DO SPRING PARA O ARQUIVO INTERNO DO CONTAINER
      - LOGGING_FILE_NAME=/app/logs/application.log
    volumes:
      # CRIA A PONTE DA SUA MÁQUINA LOCAL PARA A PASTA DE LOGS DA API
      - ./logs:/app/logs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-container
    restart: always
    environment:
      - GRAFANA_LOKI_URL:${GRAFANA_LOKI_URL}
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      # O PROMTAIL LÊ DIRETO DA PASTA COMPARTILHADA LOCALMENTE
      - ./logs:/var/log/api:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    depends_on:
      - api-comandvoice