server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${GRAFANA_LOKI_URL}

scrape_configs:
  - job_name: springboot-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: api-comandvoice
          container: api-comandvoice-container
          __path__: /var/log/api/*.log