spring:
  application:
    name: api-comandvoice
  datasource:
    url: ''
    username: ''
    password: ''
    driver-class-name: org.postgres.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

# logs em JSON
logging:
  structured:
    format:
      console: ecs

app:
  integration:
    n8n:
      webhook-url: ${N8N_WEBHOOK_URL:https://n8n.derikdev.cloud/webhook-test/comand-voice}